FROM dpage/pgadmin4:latest

# Copy your servers.json file into the image
COPY servers.json /pgadmin4/servers.json

# # Optional: Pre-populate pgadmin4.db
# COPY pgadmin4.db /var/lib/pgadmin/pgadmin4.db
