name: ADMIN-POSTGRADUATE
services:
  postgres:
    # image: postgres
    container_name: postgres-container
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.example
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: "p@p.p"
      PGADMIN_DEFAULT_PASSWORD: "p"
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./pgadmin/pgadmin4.conf:/pgadmin4/config_local.py
      - ./pgadmin/servers.json:/pgadmin4/servers.json

volumes:
  postgres_data:
