# Generated by Django 5.1 on 2025-01-02 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cohorte',
            fields=[
                ('codigo_cohorte', models.TextField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('sede_cohorte', models.TextField()),
                ('profesor_cohorte', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Datos_basicos',
            fields=[
                ('cedula', models.TextField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('tipo_usuario', models.IntegerField()),
                ('contraseña', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='datos_maestria',
            fields=[
                ('cod_maestria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_maestria', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('codigo_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_rol', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='estudiante_datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_ingreso', models.TextField()),
                ('status', models.BooleanField()),
                ('carrera', models.TextField()),
                ('cedula_estudiante', models.ForeignKey(db_column='cedula_estudiante', on_delete=django.db.models.deletion.CASCADE, to='main.datos_basicos')),
                ('cod_maestria', models.ForeignKey(db_column='cod_maestria', on_delete=django.db.models.deletion.CASCADE, to='main.datos_maestria')),
            ],
        ),
        migrations.CreateModel(
            name='materias_pensum',
            fields=[
                ('cod_materia', models.TextField(primary_key=True, serialize=False)),
                ('nombre_materia', models.TextField()),
                ('profesor_materia', models.TextField()),
                ('cod_maestria', models.ForeignKey(db_column='cod_maestria', on_delete=django.db.models.deletion.CASCADE, to='main.datos_maestria')),
            ],
        ),
        migrations.CreateModel(
            name='listado_estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('nombre_materia', models.TextField()),
                ('profesor_ci', models.TextField()),
                ('nombre_profesor_ci', models.TextField()),
                ('cedula_estudiante', models.ForeignKey(db_column='cedula_estudiante', on_delete=django.db.models.deletion.CASCADE, to='main.datos_basicos')),
                ('codigo_cohorte', models.ForeignKey(db_column='codigo_cohorte', on_delete=django.db.models.deletion.CASCADE, to='main.cohorte')),
                ('cod_materia', models.ForeignKey(db_column='cod_materia', on_delete=django.db.models.deletion.CASCADE, to='main.materias_pensum')),
            ],
        ),
        migrations.CreateModel(
            name='profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.TextField()),
                ('ci_profesor', models.ForeignKey(db_column='ci_profesor', on_delete=django.db.models.deletion.CASCADE, to='main.datos_basicos')),
                ('cod_maestria_prof', models.ForeignKey(db_column='cod_maestria_prof', on_delete=django.db.models.deletion.CASCADE, to='main.datos_maestria')),
            ],
        ),
        migrations.CreateModel(
            name='datos_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contraseña_usuario', models.TextField()),
                ('cedula_usuario', models.ForeignKey(db_column='cedula_usuario', on_delete=django.db.models.deletion.CASCADE, to='main.datos_basicos')),
                ('tipo_usuario', models.ForeignKey(db_column='tipo_usuario', on_delete=django.db.models.deletion.CASCADE, to='main.roles')),
            ],
        ),
        migrations.CreateModel(
            name='tabla_pagos',
            fields=[
                ('numero_referencia', models.IntegerField(primary_key=True, serialize=False)),
                ('banco_pago', models.TextField()),
                ('fecha_pago', models.DateTimeField()),
                ('monto_pago', models.IntegerField()),
                ('cedula_responsable', models.ForeignKey(db_column='cedula_responsable', on_delete=django.db.models.deletion.CASCADE, to='main.datos_basicos')),
            ],
        ),
        migrations.CreateModel(
            name='tabla_solicitudes',
            fields=[
                ('cod_solicitudes', models.TextField(primary_key=True, serialize=False)),
                ('nombre_estudiante', models.TextField()),
                ('apellido_estudiante', models.TextField()),
                ('fecha_solicitud', models.DateTimeField()),
                ('status_solicitud', models.TextField()),
                ('tipo_solicitud', models.TextField()),
                ('cedula_responsable', models.ForeignKey(db_column='cedula_responsable', on_delete=django.db.models.deletion.CASCADE, to='main.datos_basicos')),
            ],
        ),
    ]
