# Generated by Django 5.1 on 2025-01-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_cohorte_profesor_cohorte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante_datos',
            name='apellido_est',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante_datos',
            name='nombre_est',
            field=models.TextField(blank=True, null=True),
        ),
    ]
