# Generated by Django 5.1 on 2025-01-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_estudiante_datos_apellido_est_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante_datos',
            name='status',
        ),
        migrations.AddField(
            model_name='estudiante_datos',
            name='estado_estudiante',
            field=models.TextField(blank=True),
        ),
    ]
