# Generated by Django 5.1 on 2025-01-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_estudiante_datos_estado_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_basicos',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
