# Generated by Django 5.1 on 2025-01-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_listado_estudiantes_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohorte',
            name='tipo_maestria',
            field=models.CharField(blank=True, choices=[('GG', 'Cs Administrativas / Gerencia General (GG)'), ('FI', 'Cs Administrativas / Finanzas (FI)'), ('RH', 'Cs Administrativas / Gerencia de Recursos Humanos (RRHH)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cohorte',
            name='sede_cohorte',
            field=models.CharField(choices=[('barcelona', 'Barcelona'), ('cantaura', 'Cantaura')], max_length=50),
        ),
    ]
