# Generated by Django 5.1 on 2025-01-28 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_materias_pensum_cedula_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesores',
            name='cod_maestria_prof',
            field=models.ForeignKey(db_column='cod_maestria_prof', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.datos_maestria'),
        ),
    ]
