# Generated by Django 5.1 on 2025-02-02 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_profesores_cod_maestria_prof'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificacionProfesor',
            fields=[
                ('codplanificacion', models.CharField(db_column='codplanificacion', max_length=50, primary_key=True, serialize=False)),
                ('actividades_planificacion', models.TextField(blank=True, null=True)),
                ('actividades_porcentaje', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='listado_estudiantes',
            name='codplanificacion',
            field=models.ForeignKey(blank=True, db_column='codplanificacion', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.planificacionprofesor'),
        ),
    ]
