# Generated by Django 5.1 on 2025-02-02 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_planificacionprofesor_cod_materia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacionprofesor',
            name='cedula_profesor',
            field=models.ForeignKey(blank=True, db_column='cedula_profesor', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.datos_basicos'),
        ),
    ]
