# Generated by Django 5.1 on 2025-02-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_planificacionprofesor_cedula_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabla_pagos',
            name='estado_pago',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('Negado', 'Negado')], default='Pendiente', max_length=10),
        ),
    ]
