# Generated by Django 5.1 on 2025-02-15 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_tabla_pagos_estado_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignarProfesorMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profesor', models.TextField(blank=True, null=True)),
                ('apellido_profesor', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True)),
                ('fecha_fin', models.DateTimeField(blank=True)),
                ('cedula_profesor', models.ForeignKey(blank=True, db_column='cedula_profesor', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.datos_basicos')),
                ('cod_materia', models.ForeignKey(blank=True, db_column='cod_materia', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.materias_pensum')),
                ('codigo_cohorte', models.ForeignKey(blank=True, db_column='codigo_cohorte', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cohorte')),
            ],
        ),
    ]
