# Generated by Django 5.1 on 2025-02-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_asignarprofesormateria'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignarprofesormateria',
            name='nom_materia',
            field=models.TextField(blank=True),
        ),
    ]
