# Generated by Django 5.1 on 2025-02-15 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_planificacionprofesor_nombre_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materias_pensum',
            name='ape_profesor_materia',
        ),
        migrations.RemoveField(
            model_name='materias_pensum',
            name='cedula_profesor',
        ),
        migrations.RemoveField(
            model_name='materias_pensum',
            name='nom_profesor_materia',
        ),
    ]
